apiVersion: v1
kind: Service
metadata:
    name: "greenmail"
spec:
  ports:
    - name: "3993"
      port: 3993
      targetPort: 3993
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: greenmail
  type: LoadBalancer
status:
  loadBalancer: {}
